In [ ]:
# The first line contains two space separated integers, N and M.
# The next N lines contains M space separated integers of array A.
# The following N lines contains M space separated integers of array B.

# Sample Input

# 1 4
# 1 2 3 4
# 5 6 7 8
# Sample Output

# [[ 6  8 10 12]]
# [[-4 -4 -4 -4]]
# [[ 5 12 21 32]]
# [[0 0 0 0]]
# [[1 2 3 4]]
# [[    1    64  2187 65536]] 
import numpy

import numpy

x = numpy.array([input().strip().split(' ')], dtype=int)
a = numpy.array([input().strip().split(' ') for i in range(int(x[0][0]))], dtype=int)
b = numpy.array([input().strip().split(' ') for i in range(int(x[0][0]))], dtype=int)

print(numpy.add(a,b))
print(numpy.subtract(a, b))
print(numpy.multiply(a, b))
print(numpy.floor_divide(a,b))
print(numpy.mod(a, b))
print(numpy.power(a, b))